##spring.application.name=myProject
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/myProject
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      #      ddl-auto: none
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/myProject
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true